config/routes.rb
Rails.application.routes.draw do
  get 'operating_systems/index'

  get 'operating_systems/show'

  get 'operating_systems/edit'

  get 'operating_systems/new'
  get 'operating_systems/sample'

  resources :recipes
  resources :colleages
  resources :wine_marts
  get 'samples/get_sample'
  get 'samples/get_sample2'
  get 'samples/get_sample3'

  get 'students/get_student'
  get 'students/get_student2'
  get 'students/get_student3'

  resources :cards do
    member do
      get 'rename_first_record'
      get  'rename_second_record'
    end
          collection do
            get 'rename_first_ten_records'
          end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/colleage.rb
class Colleage < ApplicationController
end

app/controllers/colleages_controller.rb
 class ColleagesController < ApplicationController
  before_action :set_colleage, only: [:show, :edit, :update, :destroy]

  # GET /colleages
  # GET /colleages.json
  def index
    @colleages = Colleage.all
  end


  # GET /colleages/1
  # GET /colleages/1.json
  def show
  end

  # GET /colleages/new
  def new
    @colleage = Colleage.new
  end

  # GET /colleages/1/edit
  def edit
  end

  # POST /colleages
  # POST /colleages.json
  def create
    @colleage = Colleage.new(colleage_params)

    respond_to do |format|
      if @colleage.save
        format.html { redirect_to @colleage, notice: 'Colleage was successfully created.' }
        format.json { render :show, status: :created, location: @colleage }
      else
        format.html { render :new }
        format.json { render json: @colleage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleages/1
  # PATCH/PUT /colleages/1.json
  def update
    respond_to do |format|
      if @colleage.update(colleage_params)
        format.html { redirect_to @colleage, notice: 'Colleage was successfully updated.' }
        format.json { render :show, status: :ok, location: @colleage }
      else
        format.html { render :edit }
        format.json { render json: @colleage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleages/1
  # DELETE /colleages/1.json
  def destroy
    @colleage.destroy
    respond_to do |format|
      format.html { redirect_to colleages_url, notice: 'Colleage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colleage
      @colleage = Colleage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colleage_params
      params.require(:colleage).permit(:name, :city, :address, :phonenumber)
    end
  end

app/helpers/colleages_helper.rb
module ColleagesHelper
end

app/views/colleages/_form.html.erb
<%= form_for(colleage) do |f| %>
  <% if colleage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colleage.errors.count, "error") %> prohibited this colleage from being saved:</h2>

      <ul>
      <% colleage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleages/edit.html.erb
<h1>Editing Colleage</h1>

<%= render 'form', colleage: @colleage %>

<%= link_to 'Show', @colleage %> |
<%= link_to 'Back', colleages_path %>

app/views/colleages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Address</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleages.each do |colleage| %>
      <tr>
        <td><%= colleage.name %></td>
        <td><%= colleage.city %></td>
        <td><%= colleage.address %></td>
        <td><%= colleage.phonenumber %></td>
        <td><%= link_to 'Show', colleage %></td>
        <td><%= link_to 'Edit', edit_colleage_path(colleage) %></td>
        <td><%= link_to 'Destroy', colleage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>





<%= link_to 'New Colleage', new_colleage_path %>

app/views/colleages/new.html.erb
<h1>New Colleage</h1>

<%= render 'form', colleage: @colleage %>

<%= link_to 'Back', colleages_path %>

app/views/colleages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @colleage.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @colleage.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @colleage.address %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @colleage.phonenumber %>
</p>

<%= link_to 'Edit', edit_colleage_path(@colleage) %> |
<%= link_to 'Back', colleages_path %>