config/routes.rb
Rails.application.routes.draw do
  get 'operating_systems/index'

  get 'operating_systems/show'

  get 'operating_systems/edit'

  get 'operating_systems/new'
  get 'operating_systems/sample'

  resources :recipes
  resources :colleages
  resources :wine_marts
  get 'samples/get_sample'
  get 'samples/get_sample2'
  get 'samples/get_sample3'

  get 'students/get_student'
  get 'students/get_student2'
  get 'students/get_student3'

  resources :cards do
    member do
      get 'rename_first_record'
      get  'rename_second_record'
    end
          collection do
            get 'rename_first_ten_records'
          end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

def index
  @cards= Card.all
 end

def show
  @cards = Card.find(params[:id])
end

def new
	@card = Card.new
end

def create
	@card = Card.new(card_params)
	@card.save
	redirect_to cards_path
	end
	def edit
		@cards = Card.find(parms[:id])
	end
    
    def Update
    	@card = Card.find(parms[:id])
    	@card = Card.update(card_params)
    	redirect_to cards_path
    end
    def Destroy
    	 @card = Card.find(params[:id])
    	  @card.destroy
    	  respond_to do |format|
     	format.html {redirect_to cards_url}

    	 # 	 respond_to do |format|
      # format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      # format.json { head :no_content }
   
    end
  end
    def rename_first_record
      @card = Card.find(params[:id])
      @card.name = "card updated  from member action"
      @card.save
      redirect_to cards_path
     end
     def rename_second_record
      @card = Card.find(params[:id])
      @card.name = "card updated from member action 2"
      @cards.save
      redirect_to cards_path
     end
     def rename_first_ten_records
      @cards = Card.first(10)
      @cards.each do |card|
        @card.name = "card updated member from member action venkey"
        @card.save
    end
     redirect_to cards_path
 end 
     
    private 
      def card_params
      	params.require(:card).permit(:name,:category,:industry)
      end

     
end

app/views/cards/edit.html.erb
<h1> creating new card</h1>
<%= form_for(@card) do |f| %>

<div>
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
 

<div>
	<%= f.label :category %>
	<%= f.text_field :category %>
</div>

<div>
	<%= f.label :industry %>
	<%= f.text_field :industry %>
</div>

<div>
	<%= f.submit "create software" %>
</div>
<% end %>
<p>
	<%= link_to "create card", new_card_path %>
</p>

<p>
	<%= link_to "Back", cards_path %>
</p>

app/views/cards/index.html.erb
<h1> Cards </h1>

<table>
	<thead> 
		<tr>
		<th>name</th>
		<th>category</th>
		<th>industry</th>
		</tr>
	</thead>
	<tbody>
		<% @cards.each do |card| %>
		<tr>
			<td><%= card.name %></td>
			<td><%= card.category %></td>
			<td><%= card.industry %></td>
			<td><%= link_to 'show', card_path(card) %></td>
			<td><%= link_to 'edit', card_path(card) %></td>
			<td><%= link_to 'Destroy', card,method: :delete,data: {confirm:'Are you sure?'} %></td>

		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to  "new card",new_card_path %>


	

app/views/cards/new.html.erb
<h1> creating new card</h1>
<%= form_for(@card) do |f| %>

<div>
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
 

<div>
	<%= f.label :category %>
	<%= f.text_field :category %>
</div>

<div>
	<%= f.label :industry %>
	<%= f.text_field :industry %>
</div>

<div>
	<%= f.submit "create software" %>
</div>
<% end %>

<p>
	<%= link_to "Back", cards_path %>
</p>

app/views/cards/rename_first_record.html.erb
show sample

app/views/cards/rename_first_ten_records.html.erb
show sample

app/views/cards/rename_second_record.html.erb
show samplw

app/views/cards/show.html.erb
<h1> Details</h1>
<p>
	<strong>name:</strong>
	<%= @cards.name %>

</p>

<p>
	<strong>category:</strong>
	<%= @cards.category %>
</p>
<p>
	<strong>industry:</strong>
	<%= @cards.industry %>
</p>
<p>
	<%= link_to "back",cards_path %>
</p>