config/routes.rb
Rails.application.routes.draw do
  get 'operating_systems/index'

  get 'operating_systems/show'

  get 'operating_systems/edit'

  get 'operating_systems/new'
  get 'operating_systems/sample'

  resources :recipes
  resources :colleages
  resources :wine_marts
  get 'samples/get_sample'
  get 'samples/get_sample2'
  get 'samples/get_sample3'

  get 'students/get_student'
  get 'students/get_student2'
  get 'students/get_student3'

  resources :cards do
    member do
      get 'rename_first_record'
      get  'rename_second_record'
    end
          collection do
            get 'rename_first_ten_records'
          end
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine_mart.rb
class WineMart < ApplicationRecord
end

app/controllers/wine_marts_controller.rb
class WineMartsController < ApplicationController
	def index
		@wine_marts = WineMart.all
	end
	def show
		@wine_mart = WineMart.find(params[:id])
	end

	def new
		@wine_mart = WineMart.new
	end

	def create
		@wine_mart = WineMart.new(wine_mart_params)
		@wine_mart.save
	    redirect_to wine_mart_path(@wine_mart)
	     
	end

	def update
		@wine_mart = WineMart.find(params[:id])
		@wine_mart.update(wine_mart_params)
		redirect_towine_mart_path
	end

	def destroy
		@wine_mart = WineMart.find(params[:id])
		@wine_mart.destroy
		redirect_to wine_mart_path
	end
	private 
	 def wine_mart_params
	 	params.require(:wine_mart).permit(:name,:category,:industry)
      end
  end

app/views/wine_marts/edit.html.erb
<h1> Creating New Wine Mart</h1>

<% = form_for(@wine_mart) do |f| %>

<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :industry %>
    <%= f.text_field :industry %>
  </div>

  <div class="actions">
    <%= f.submit  "create new Wine Mart"%>
  </div>
<% end %>

app/views/wine_marts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Wine Marts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Industry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wine_marts.each do |wine_mart| %>
      <tr>
        <td><%= wine_mart.name %></td>
        <td><%= wine_mart.category %></td>
        <td><%= wine_mart.industry %></td>
        <td><%= link_to 'Show', wine_mart_path(wine_mart) %></td>
        <td><%= link_to 'Edit', edit_wine_mart_path(wine_mart) %></td>
        <td><%= link_to 'Destroy', wine_mart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><%= link_to 'Create Wine Mart', new_wine_mart_path %></td>

app/views/wine_marts/new.html.erb
<h1> Creating New Wine Mart</h1>
<h1>Wine Mart</h1>
<%= form_for(@wine_mart) do |f| %>

<div class ="field">
<%= f.label :name %>
<%= f.text_field :name %>
</div>

<div class ="field">
<%= f.label :category %>
<%= f.text_field :category %>
</div>
<div class ="field">
<%= f.label :industry %>
<%= f.text_field :industry %>
</div>

<div class ="actions">
<%= f.submit "create new wine mart" %>
</div>


<% end %>

app/views/wine_marts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine_mart.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @wine_mart.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @wine_mart.industry %>
</p>
<td><%= link_to 'Create Wine Mart ', new_wine_mart_path %></td>
<%= link_to 'Back', wine_mart_path %>